// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Organization struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Settings    pqtype.NullRawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Task struct {
	ID          uuid.UUID
	Title       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
	UserID      uuid.UUID
	Description string
	IsCompleted bool
}

type User struct {
	ID             uuid.UUID
	Username       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ApiKey         string
	PasswordHash   string
	Age            sql.NullInt32
	Gender         sql.NullString
	Role           string
	OrganizationID uuid.NullUUID
}
